from enum import Enum


class RequestID(Enum):
    TEXT_TO_SPEECH_AUDIO = 0
    TEXT_TO_SPEECH_STREAM = 1
    GET_VOICES = 2
    GET_DEFAULT_VOICE_SETTINGS = 3
    GET_VOICE_SETTINGS = 4
    GET_VOICE = 5
    DELETE_VOICE = 6
    EDIT_VOICE_SETTINGS = 7
    ADD_VOICE = 8
    EDIT_VOICE = 9
    DELETE_SAMPLE = 10
    GET_AUDIO_FROM_SAMPLE = 11
    GET_GENERATED_ITEMS = 12
    GET_AUDIO_FROM_HISTORY_ITEM = 13
    DELETE_HISTORY_ITEM = 14
    DOWNLOAD_HISTORY_ITEMS = 15
    GET_USER_SUBSCRIPTION_INFO = 16
    GET_USER_INFO = 17
